name: CI
on: [push, pull_request]

jobs:
  Build-and-Test:
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        dbg: [OFF, ON]
        cxx: [g++,clang++]
    name: On ${{ matrix.os }} (DBG=${{ matrix.dbg }}) (CXX=${{ matrix.cxx }})
    runs-on: ${{ matrix.os }}
    env:
      QD_DBG: ${{ matrix.dbg }}
      QD_CXX: ${{ matrix.cxx }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install packages
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y libnuma-dev
      - name: Before install
        run: ./.github/scripts/get_gtest.sh
      - name: Build
        run: ./.github/scripts/make_qd.sh
      - name: Test
        run: cd build && make test
